version: "3.1"
name: ecommerce
services:
  db:
    image: mysql
    restart: unless-stopped
    env_file: mysql.env
    volumes:
      - ./.database:/var/lib/mysql

  api:
    image: ghcr.io/geras4323/ecommerce-backend:latest
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${BASE_DOMAIN}`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=resolver"
    volumes:
      - ./api.env:/usr/src/.env
    ports:
      - 3000:1323

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./watchtower.json:/config.json
    command:
      - "--interval=${WATCHTOWER_INTERVAL}"
      - "--label-enable"
      - "--notification-url=${WATCHTOWER_NOTIFICATION_URL}"

  traefik:
    image: traefik:v2.10
    restart: unless-stopped
    command:
      # LOGS AND DASHBOARD
      - "--log.level=INFO"
      # - "--api.insecure=true"

      # PROVIDER SETTINGS
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"

      # ENTRY-POINTS SETTINGS
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"

      #ACME Config
      - "--certificatesresolvers.resolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.resolver.acme.storage=acme.json"
      - "--certificatesresolvers.resolver.acme.httpchallenge.entrypoint=web"
      # - "--certificatesresolvers.resolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
      - ./letsencrypt:/letsencrypt
